[workspace]
members = ["client", "common", "server"]
resolver = "2"

[workspace.package]
version = "0.0.0"
description = "A chat client and server for nerdserver"
authors = ["Ethan Uppal"]
rust-version = "1.79"
edition = "2021"

[workspace.dependencies]
