[package]
name = "chat"
version.workspace = true
description.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
serde.workspace = true
