[package]
name = "comms"
version.workspace = true
description.workspace = true
authors.workspace = true
rust-version.workspace = true
edition.workspace = true

[dependencies]
chat.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
