name: Code Style

on:
  pull_request:
  push:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rust Caching
        uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build
      - name: Lint
        run: cargo clippy
      - name: Check formatting
        run: cargo +nightly fmt --check
