# https://github.com/folke/github/blob/main/.github/workflows/pr.yml
name: PR Style

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    branches: [main]

jobs:
  title-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          requireScope: true
          ignoreLabels: |
            autorelease: pending
  # https://stackoverflow.com/questions/70929443/how-to-create-an-automatic-github-comment-based-on-the-pull-request-title
  comment:
    runs-on: ubuntu-latest
    if: "startsWith(github.event.pull_request.title, 'perf')"
    steps:
      - uses: actions/github-script@v5
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'It looks like you\'ve made a PR with performance improvements. Make sure you add benchmarks to prove that your changes are actually worthwhile.'
            })
