on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    environment:
      name: release-please
    steps:
      - uses: googleapis/release-please-action@v4
